import { Recipe } from '@/types';

export const recipes: Recipe[] = [
  {
    id: 'chicken-lemon',
    title: '鶏むね肉のレモンハーブ焼き定食',
    cuisine: 'western',
    calories: 720,
    protein: 55,
    fat: 12,
    carbs: 75,
    cookMinutes: 20,
    ingredients: ['鶏むね肉 200g', 'ブロッコリー', '玄米 120g', 'わかめスープ'],
    shoppingList: ['鶏むね肉', 'レモン', 'ブロッコリー', '玄米'],
    alternatives: ['サバの塩焼き定食', '豆腐ハンバーグ定食'],
    seasonalTags: ['ブロッコリー', 'レモン']
  },
  {
    id: 'saba-set',
    title: 'サバの塩焼き定食',
    cuisine: 'japanese',
    calories: 680,
    protein: 42,
    fat: 24,
    carbs: 63,
    cookMinutes: 18,
    ingredients: ['サバ切り身', '雑穀ごはん', 'ほうれん草おひたし', '味噌汁'],
    shoppingList: ['サバ', '雑穀米', 'ほうれん草', '味噌'],
    alternatives: ['鮭の幽庵焼き', 'カツオのたたき定食'],
    seasonalTags: ['サバ', 'ほうれん草']
  },
  {
    id: 'tofu-hamburg',
    title: '豆腐ハンバーグ定食',
    cuisine: 'japanese',
    calories: 610,
    protein: 38,
    fat: 16,
    carbs: 71,
    cookMinutes: 25,
    ingredients: ['木綿豆腐', '鶏ひき肉', '大根おろし', 'ごはん', 'きのこ汁'],
    shoppingList: ['木綿豆腐', '鶏ひき肉', '大根', 'しめじ'],
    alternatives: ['湯豆腐定食', '親子丼'],
    seasonalTags: ['大根', 'きのこ']
  },
  {
    id: 'salmon-yuan',
    title: '鮭の幽庵焼きと雑穀ごはん',
    cuisine: 'japanese',
    calories: 640,
    protein: 41,
    fat: 18,
    carbs: 70,
    cookMinutes: 22,
    ingredients: ['鮭', '雑穀ごはん', '小松菜胡麻和え', '豆腐味噌汁'],
    shoppingList: ['鮭', '雑穀米', '小松菜', '豆腐'],
    alternatives: ['サバの塩焼き定食', '鶏照り焼きプレート'],
    seasonalTags: ['鮭']
  },
  {
    id: 'mapo-tofu',
    title: '低脂質 麻婆豆腐プレート',
    cuisine: 'chinese',
    calories: 690,
    protein: 45,
    fat: 19,
    carbs: 74,
    cookMinutes: 20,
    ingredients: ['木綿豆腐', '豚赤身ひき肉', '長ねぎ', 'ごはん', '中華スープ'],
    shoppingList: ['豆腐', '豚赤身ひき肉', '長ねぎ', '豆板醤'],
    alternatives: ['青椒肉絲プレート', '油淋鶏ライト'],
    seasonalTags: ['長ねぎ']
  },
  {
    id: 'oyakodon',
    title: '高たんぱく親子丼',
    cuisine: 'japanese',
    calories: 710,
    protein: 44,
    fat: 17,
    carbs: 86,
    cookMinutes: 15,
    ingredients: ['鶏もも皮なし', '卵 2個', '玉ねぎ', 'ごはん', '味噌汁'],
    shoppingList: ['鶏もも肉', '卵', '玉ねぎ'],
    alternatives: ['牛丼ライト', '鶏そぼろ丼'],
    seasonalTags: ['玉ねぎ']
  },
  {
    id: 'gyudon-lite',
    title: '牛丼ライトとサラダ',
    cuisine: 'japanese',
    calories: 760,
    protein: 39,
    fat: 22,
    carbs: 88,
    cookMinutes: 18,
    ingredients: ['牛もも肉', '玉ねぎ', 'ごはん', '海藻サラダ'],
    shoppingList: ['牛もも肉', '玉ねぎ', '海藻ミックス'],
    alternatives: ['親子丼', '生姜焼き定食'],
    seasonalTags: ['玉ねぎ']
  },
  {
    id: 'ginger-pork',
    title: '豚ヒレの生姜焼き定食',
    cuisine: 'japanese',
    calories: 700,
    protein: 43,
    fat: 18,
    carbs: 79,
    cookMinutes: 20,
    ingredients: ['豚ヒレ肉', 'キャベツ', 'ごはん', '豆腐味噌汁'],
    shoppingList: ['豚ヒレ肉', '生姜', 'キャベツ', '豆腐'],
    alternatives: ['牛丼ライト', 'チキンソテー'],
    seasonalTags: ['キャベツ']
  },
  {
    id: 'katsuo-tataki',
    title: 'カツオのたたき定食',
    cuisine: 'japanese',
    calories: 620,
    protein: 47,
    fat: 11,
    carbs: 72,
    cookMinutes: 12,
    ingredients: ['カツオたたき', '雑穀ごはん', '冷奴', 'すまし汁'],
    shoppingList: ['カツオ', '雑穀米', '豆腐', '大葉'],
    alternatives: ['鮭の幽庵焼き', '鶏むね肉のレモンハーブ焼き定食'],
    seasonalTags: ['鰹']
  },
  {
    id: 'yudofu',
    title: '湯豆腐と鶏ささみの定食',
    cuisine: 'japanese',
    calories: 560,
    protein: 40,
    fat: 12,
    carbs: 63,
    cookMinutes: 15,
    ingredients: ['豆腐', '鶏ささみ', '白菜', 'しいたけ', 'ごはん'],
    shoppingList: ['豆腐', '鶏ささみ', '白菜', 'しいたけ'],
    alternatives: ['豆腐ハンバーグ定食', '麻婆豆腐プレート'],
    seasonalTags: ['白菜', 'しいたけ']
  },
  {
    id: 'chinjao',
    title: '青椒肉絲プレート',
    cuisine: 'chinese',
    calories: 730,
    protein: 40,
    fat: 20,
    carbs: 83,
    cookMinutes: 18,
    ingredients: ['牛もも肉', 'ピーマン', 'たけのこ', 'ごはん'],
    shoppingList: ['牛もも肉', 'ピーマン', 'たけのこ'],
    alternatives: ['麻婆豆腐プレート', '回鍋肉ライト'],
    seasonalTags: ['たけのこ', 'ピーマン']
  },
  {
    id: 'hakkou-miso-chicken',
    title: '発酵味噌チキンプレート',
    cuisine: 'japanese',
    calories: 670,
    protein: 48,
    fat: 15,
    carbs: 71,
    cookMinutes: 25,
    ingredients: ['鶏もも皮なし', '味噌', 'さつまいも', 'サラダ'],
    shoppingList: ['鶏もも肉', '味噌', 'さつまいも', 'レタス'],
    alternatives: ['鶏むね肉のレモンハーブ焼き定食', '鮭の幽庵焼きと雑穀ごはん'],
    seasonalTags: ['さつまいも']
  },
  {
    id: 'poke-bowl',
    title: 'まぐろポキ丼',
    cuisine: 'western',
    calories: 690,
    protein: 46,
    fat: 14,
    carbs: 84,
    cookMinutes: 10,
    ingredients: ['まぐろ赤身', 'アボカド', 'ごはん', '海藻'],
    shoppingList: ['まぐろ赤身', 'アボカド', '海藻'],
    alternatives: ['カツオのたたき定食', 'サーモンライスボウル'],
    seasonalTags: ['まぐろ']
  },
  {
    id: 'salmon-rice-bowl',
    title: 'サーモンライスボウル',
    cuisine: 'western',
    calories: 710,
    protein: 41,
    fat: 19,
    carbs: 82,
    cookMinutes: 12,
    ingredients: ['サーモン', '雑穀ごはん', '温泉卵', 'アスパラ'],
    shoppingList: ['サーモン', '卵', 'アスパラ', '雑穀米'],
    alternatives: ['まぐろポキ丼', '鮭の幽庵焼きと雑穀ごはん'],
    seasonalTags: ['アスパラ']
  },
  {
    id: 'chicken-curry-lite',
    title: 'チキンカレーライト',
    cuisine: 'western',
    calories: 760,
    protein: 43,
    fat: 17,
    carbs: 96,
    cookMinutes: 25,
    ingredients: ['鶏むね肉', 'じゃがいも', 'にんじん', 'ごはん'],
    shoppingList: ['鶏むね肉', 'じゃがいも', 'にんじん', 'カレールー'],
    alternatives: ['親子丼', '青椒肉絲プレート'],
    seasonalTags: ['にんじん']
  },
  {
    id: 'tori-soboro',
    title: '鶏そぼろ丼と温野菜',
    cuisine: 'japanese',
    calories: 650,
    protein: 42,
    fat: 14,
    carbs: 81,
    cookMinutes: 15,
    ingredients: ['鶏ひき肉', '卵', 'ごはん', 'ブロッコリー'],
    shoppingList: ['鶏ひき肉', '卵', 'ブロッコリー'],
    alternatives: ['親子丼', '発酵味噌チキンプレート'],
    seasonalTags: ['ブロッコリー']
  },
  {
    id: 'hoikoro-lite',
    title: '回鍋肉ライト定食',
    cuisine: 'chinese',
    calories: 740,
    protein: 38,
    fat: 21,
    carbs: 85,
    cookMinutes: 20,
    ingredients: ['豚もも肉', 'キャベツ', 'ピーマン', 'ごはん'],
    shoppingList: ['豚もも肉', 'キャベツ', 'ピーマン', '甜麺醤'],
    alternatives: ['青椒肉絲プレート', '生姜焼き定食'],
    seasonalTags: ['キャベツ', 'ピーマン']
  },
  {
    id: 'tuna-pasta',
    title: 'ツナときのこの和風パスタ',
    cuisine: 'western',
    calories: 700,
    protein: 36,
    fat: 14,
    carbs: 96,
    cookMinutes: 18,
    ingredients: ['全粒粉パスタ', 'ツナ', 'しめじ', '大葉'],
    shoppingList: ['全粒粉パスタ', 'ツナ', 'しめじ', '大葉'],
    alternatives: ['チキンカレーライト', 'サーモンライスボウル'],
    seasonalTags: ['きのこ']
  },
  {
    id: 'beef-stew-lite',
    title: 'ビーフシチューライト',
    cuisine: 'western',
    calories: 730,
    protein: 40,
    fat: 20,
    carbs: 78,
    cookMinutes: 30,
    ingredients: ['牛もも肉', 'にんじん', 'じゃがいも', 'パン'],
    shoppingList: ['牛もも肉', 'にんじん', 'じゃがいも', 'ブロッコリー'],
    alternatives: ['発酵味噌チキンプレート', '豚ヒレの生姜焼き定食'],
    seasonalTags: ['にんじん']
  },
  {
    id: 'shrimp-stirfry',
    title: '海老とブロッコリーの塩炒め',
    cuisine: 'chinese',
    calories: 620,
    protein: 43,
    fat: 10,
    carbs: 79,
    cookMinutes: 17,
    ingredients: ['海老', 'ブロッコリー', '卵白炒飯'],
    shoppingList: ['海老', 'ブロッコリー', '卵', '米'],
    alternatives: ['麻婆豆腐プレート', '青椒肉絲プレート'],
    seasonalTags: ['ブロッコリー']
  },
  {
    id: 'seasonal-bamboo',
    title: '筍ごはんと鶏つくね汁',
    cuisine: 'japanese',
    calories: 670,
    protein: 39,
    fat: 14,
    carbs: 90,
    cookMinutes: 25,
    ingredients: ['筍ごはん', '鶏つくね', '菜の花おひたし'],
    shoppingList: ['筍', '鶏ひき肉', '菜の花'],
    alternatives: ['鶏そぼろ丼と温野菜', '湯豆腐と鶏ささみの定食'],
    seasonalTags: ['筍', '菜の花']
  },
  {
    id: 'seasonal-mushroom',
    title: 'きのこ炊き込みご飯と鮭定食',
    cuisine: 'japanese',
    calories: 690,
    protein: 42,
    fat: 16,
    carbs: 86,
    cookMinutes: 25,
    ingredients: ['鮭', 'きのこ炊き込みご飯', '小鉢'],
    shoppingList: ['鮭', 'しめじ', 'まいたけ', '米'],
    alternatives: ['鮭の幽庵焼きと雑穀ごはん', 'サバの塩焼き定食'],
    seasonalTags: ['きのこ']
  }
];
